/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CapaPresentacion;

import cap_logica.Cliente;
import cap_logica.Cuenta;
import cap_logica.Moneda;
import cap_logica.Strings;
import java.awt.Color;
import java.sql.Date;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author Lenovo
 */
public class RegistrarCuenta extends javax.swing.JPanel {
    
    private boolean encontrado = false;

    /**
     * Creates new form PnlMtnmtRegistrarCuenta
     */
    public RegistrarCuenta() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        imgCuenta = new javax.swing.JLabel();
        txNumero = new javax.swing.JLabel();
        txFechaApertura = new javax.swing.JLabel();
        dcFechaAper = new com.toedter.calendar.JDateChooser();
        txMontoInicial = new javax.swing.JLabel();
        tfMontoInicial = new javax.swing.JTextField();
        txTipoMoneda = new javax.swing.JLabel();
        cbTipoMoneda = new javax.swing.JComboBox<>();
        txEstado = new javax.swing.JLabel();
        cbEstado = new javax.swing.JComboBox<>();
        txDniCliente = new javax.swing.JLabel();
        tfDniCliente = new javax.swing.JTextField();
        btBuscar = new javax.swing.JButton();
        btLimpiar = new javax.swing.JButton();
        btAddCuenta = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();

        setBackground(new java.awt.Color(153, 204, 255));

        imgCuenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/imgRegCuenta.jpg"))); // NOI18N

        txNumero.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txNumero.setText("Número Cuenta:");

        txFechaApertura.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txFechaApertura.setText("Fecha de Apertura:");

        dcFechaAper.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        dcFechaAper.setOpaque(false);
        dcFechaAper.setPreferredSize(new java.awt.Dimension(450, 35));

        txMontoInicial.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txMontoInicial.setText("Monto Inicial:");

        tfMontoInicial.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        tfMontoInicial.setForeground(new java.awt.Color(153, 153, 153));
        tfMontoInicial.setText(Strings.ejmMontoInicial);
        tfMontoInicial.setPreferredSize(new java.awt.Dimension(450, 35));
        tfMontoInicial.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tfMontoInicialMousePressed(evt);
            }
        });
        tfMontoInicial.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfMontoInicialKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfMontoInicialKeyReleased(evt);
            }
        });

        txTipoMoneda.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txTipoMoneda.setText("Tipo de moneda:");

        cbTipoMoneda.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        cbTipoMoneda.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "- Seleccionar -", "SOLES", "DOLARES", "EUROS" }));
        cbTipoMoneda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbTipoMonedaActionPerformed(evt);
            }
        });

        txEstado.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txEstado.setText("Estado:");

        cbEstado.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        cbEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "- Seleccionar -", "ABIERTA", "CERRADA" }));
        cbEstado.setSelectedIndex(1);
        cbEstado.setEnabled(false);

        txDniCliente.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txDniCliente.setText("DNI cliente:");

        tfDniCliente.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        tfDniCliente.setForeground(new java.awt.Color(153, 153, 153));
        tfDniCliente.setText(Strings.ejmDni);
        tfDniCliente.setPreferredSize(new java.awt.Dimension(450, 35));
        tfDniCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tfDniClienteMousePressed(evt);
            }
        });
        tfDniCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfDniClienteKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfDniClienteKeyReleased(evt);
            }
        });

        btBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/buscarx32.png"))); // NOI18N
        btBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBuscarActionPerformed(evt);
            }
        });

        btLimpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/limpiarx32.png"))); // NOI18N
        btLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimpiarActionPerformed(evt);
            }
        });

        btAddCuenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/addCuentax48.png"))); // NOI18N
        btAddCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAddCuentaActionPerformed(evt);
            }
        });

        jComboBox1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "- Seleccionar -" }));
        jComboBox1.setToolTipText("- Seleccionar -");
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(imgCuenta)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txNumero)
                    .addComponent(txFechaApertura)
                    .addComponent(txMontoInicial)
                    .addComponent(txTipoMoneda)
                    .addComponent(txEstado)
                    .addComponent(txDniCliente))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(dcFechaAper, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tfMontoInicial, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbTipoMoneda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfDniCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(128, 128, 128)
                        .addComponent(btAddCuenta))
                    .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(30, 30, 30)
                .addComponent(btBuscar)
                .addGap(10, 10, 10)
                .addComponent(btLimpiar))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(imgCuenta))
            .addGroup(layout.createSequentialGroup()
                .addGap(291, 291, 291)
                .addComponent(btBuscar))
            .addGroup(layout.createSequentialGroup()
                .addGap(291, 291, 291)
                .addComponent(btLimpiar))
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(dcFechaAper, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16)
                        .addComponent(tfMontoInicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16)
                        .addComponent(cbTipoMoneda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16)
                        .addComponent(cbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16)
                        .addComponent(tfDniCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(btAddCuenta))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txNumero)
                        .addGap(20, 20, 20)
                        .addComponent(txFechaApertura)
                        .addGap(22, 22, 22)
                        .addComponent(txMontoInicial)
                        .addGap(22, 22, 22)
                        .addComponent(txTipoMoneda)
                        .addGap(22, 22, 22)
                        .addComponent(txEstado)
                        .addGap(22, 22, 22)
                        .addComponent(txDniCliente))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btAddCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAddCuentaActionPerformed
 
    }//GEN-LAST:event_btAddCuentaActionPerformed

    private void btLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimpiarActionPerformed
        // TODO add your handling code here:
    
    }//GEN-LAST:event_btLimpiarActionPerformed

    private void btBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBuscarActionPerformed
        // TODO add your handling code here:
    
        
    }//GEN-LAST:event_btBuscarActionPerformed

    private void tfMontoInicialMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfMontoInicialMousePressed
        // TODO add your handling code here:
    
    }//GEN-LAST:event_tfMontoInicialMousePressed

    private void tfMontoInicialKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfMontoInicialKeyPressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_tfMontoInicialKeyPressed

    private void tfMontoInicialKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfMontoInicialKeyReleased
        // TODO add your handling code here:
  
    }//GEN-LAST:event_tfMontoInicialKeyReleased

    private void tfDniClienteMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfDniClienteMousePressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_tfDniClienteMousePressed

    private void tfDniClienteKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfDniClienteKeyPressed
        // TODO add your handling code here:

    }//GEN-LAST:event_tfDniClienteKeyPressed

    private void tfDniClienteKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfDniClienteKeyReleased
        // TODO add your handling code here:
      
    }//GEN-LAST:event_tfDniClienteKeyReleased

    private void cbTipoMonedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbTipoMonedaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbTipoMonedaActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAddCuenta;
    private javax.swing.JButton btBuscar;
    private javax.swing.JButton btLimpiar;
    private javax.swing.JComboBox<String> cbEstado;
    private javax.swing.JComboBox<String> cbTipoMoneda;
    private com.toedter.calendar.JDateChooser dcFechaAper;
    private javax.swing.JLabel imgCuenta;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JTextField tfDniCliente;
    private javax.swing.JTextField tfMontoInicial;
    private javax.swing.JLabel txDniCliente;
    private javax.swing.JLabel txEstado;
    private javax.swing.JLabel txFechaApertura;
    private javax.swing.JLabel txMontoInicial;
    private javax.swing.JLabel txNumero;
    private javax.swing.JLabel txTipoMoneda;
    // End of variables declaration//GEN-END:variables
}
